# Generated by Django 3.1.4 on 2021-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_product_count_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
