# Generated by Django 3.2.6 on 2021-08-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_order_shipping_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.deliverydistricts', verbose_name='Район доставки'),
        ),
    ]
